In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib as plt
import seaborn as sns
import sklearn

In [2]:
df = pd.read_csv('example.csv')
df

one       two     three
0   example1  example2  example3
1         T1        T2        T3
2     Sunday    Monday   Tuesday
3  Wednesday  Thursday    Friday
4   Saturday       NaN       NaN

In [5]:
import csv

In [7]:
with open('example.csv', 'rt') as f:
    data= csv.reader(f)
    for i in data:
        print(i)

['one', 'two', 'three']
['example1', 'example2', 'example3']
['T1', 'T2', 'T3']
['Sunday', 'Monday', 'Tuesday']
['Wednesday', 'Thursday', 'Friday']
['Saturday', '', '']


In [8]:
reader=csv.DictReader(open('example.csv', 'rt'))
for i in reader:
    print(i)

{'one': 'example1', 'two': 'example2', 'three': 'example3'}
{'one': 'T1', 'two': 'T2', 'three': 'T3'}
{'one': 'Sunday', 'two': 'Monday', 'three': 'Tuesday'}
{'one': 'Wednesday', 'two': 'Thursday', 'three': 'Friday'}
{'one': 'Saturday', 'two': '', 'three': ''}


In [13]:
with open('example.csv', mode='a') as f:
    writer=csv.writer(f,delimiter=',',quotechar=",",quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['One 1','Two 2','Three 3'])

In [16]:
ass1=np.arange(9)
ass1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
ass1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
ass2=np.arange(10)

In [20]:
for i in ass2:
    if ass2[i]%2 == 1:
        ass2[i] = -1
ass2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [29]:
x=np.array([21,64,86,22,74,55,81,79,90,89])
y=np.array([21,7,3,45,10,29,55,4,37,18])
a = []
b = []

In [30]:
for i in range(10):
    if x[i] > y[i]:
        a.append(i)
    if x[i] == y[i]:
        b.append(i)

In [31]:
a

[1, 2, 4, 5, 6, 7, 8, 9]

In [32]:
b

[0]

In [33]:
ass4 = np.arange(100).reshape(5,-1)

In [36]:
ass4

In [39]:
ass4[0:, 0:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [40]:
adq1 = []
for i in range(10):
    adq1.append(np.random.randint(30,40))
adq1

[31, 38, 37, 38, 31, 39, 37, 38, 34, 32]

In [95]:
matA=np.arange(9).reshape(3,3)
matA

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
matA + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
matA[-1][-1] + 1

9

In [98]:
matA

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
matA += 1

In [100]:
matA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
matA[-1][-1] += 1

In [102]:
matA

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [103]:
matA[2]

array([ 7,  8, 10])

In [104]:
matB = np.array([7,8,10,4,5,6,1,2,3]).reshape(3,3)

In [105]:
matB

array([[ 7,  8, 10],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [106]:
matC = matA + matB

In [107]:
matC

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [108]:
matE = matA - matB

In [109]:
matE

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  7]])

In [110]:
matD = matA.dot(matB)
matD

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [111]:
matE.transpose()

array([[-6,  0,  6],
       [-6,  0,  6],
       [-7,  0,  7]])